### ISSUE TITLE
The OMK & Maps.Me buttons direct to the Play store instead of opening the apps

### ISSUE THREAD

**Issue by DaCor1** [hotosm/MapCampaigner#387]
I was under the impressions these buttons would lead to the AOI being opened directly in the apps

**Comment by smit1678** [comment]
This should be now fixed via https://github.com/hotosm/MapCampaigner/pull/640. Button downloads a KML and opens in Maps.me (depending on mobile browser you're using, it might require you to choose to open in Maps.me).
