### ISSUE TITLE
maps.me Link Downloads KML File

### ISSUE THREAD

**Issue by tordans** [hotosm/MapCampaigner#405]
Testcase:
Use google chrome on mac os.
1. open http://campaigns.hotosm.org/campaign/bc98b1f4d73c4b3fb2cc29c7bc5633b4
2. click on maps.me link
IS => downloads a .kml file
SHOULD => not do anything

Secondary:
The "OpenMapKit" Link can be clicked as well but results in an error "OpenMapKit is not available in your current device" which is a bit better but not great either.

**Comment by russbiggs** [comment]
This is the intended behavior
