### ISSUE TITLE
maps.me Link does not work iOS Chrome

### ISSUE THREAD

**Issue by tordans** [hotosm/MapCampaigner#406]
To reproduce:
Use an iPhone, Google Chrome
1. open http://campaigns.hotosm.org/campaign/bc98b1f4d73c4b3fb2cc29c7bc5633b4
2. click the maps.me link
IS => nothing happens
SHOULD => open maps.me with file/link

It does work in iOS Safari.

**Comment by smit1678** [comment]
This should be now fixed via #640. Button downloads a KML and opens in Maps.me (depending on mobile browser you're using, it might require you to choose to open in Maps.me).
