### ISSUE TITLE
deploy already existing lambda functions

### ISSUE THREAD

**Issue by pierrealixt** [hotosm/MapCampaigner#501]
# Problem

Travis is responsible to deploy lambda functions. If the lambda function already exists, it should update the function but that's not the case. It always tries to create the function and then causes an error. 

# Solution
Investigate and implement a fix.

**Comment by timlinux** [comment]
@pierrealixt has an autodeploy script but it does not work on travis currently. When he runs from his local machine it works. We need to poke around and see why the travis deploy fails. 

Time estimate: 3 hours
