### ISSUE TITLE
Map preview thumbnails not generated

### ISSUE THREAD

**Issue by smit1678** [hotosm/MapCampaigner#592]
Some previews are not being rendered on the landing page. It seems that the campaign stats are calculated correctly and the campaign page is rendered, example: https://campaigns.hotosm.org/campaign/3f6e8cc3c7ff4876bb2f48d147146451. 

<img width="1398" alt="map campaigner 2018-11-07 13-14-35" src="https://user-images.githubusercontent.com/796838/48133588-39a33c80-e28f-11e8-916e-eda305d12abb.png">

**Comment by timlinux** [comment]
Looking at the screenshot it looks like the image does not exist on the server. @pierrealixt to review the image generation code and find out the reason why and then fix the existing campaigns.

Time estimate: 4 hours

**Comment by pierrealixt** [comment]
It seems that the map box URL generated was wrong and returned a 413 error.
```
413 ERROR

The request could not be satisfied.

Bad request. 
Generated by cloudfront (CloudFront)
Request ID: 01ofynyyFySFtSVq77i9kdH400xmc9rjx2OXTeNzaHjjzgNKcJF47w==
```

My guess is that the URL is too long, for [this campaign](https://campaigns.hotosm.org/campaign/85f9c86cf13c4863833ad79faff12464), [the thumbnail URL](https://api.mapbox.com/styles/v1/hot/cj7hdldfv4d2e2qp37cm09tl8/static/geojson({"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[11.9041312093642,-4.70753666312102],[11.9105156333578,-4.7112609111538],[11.9151266055772,-4.71640391943467],[11.9223977564556,-4.71463046817797],[11.924880587913,-4.71941878660675],[11.9293142161563,-4.72190161832309],[11.9474034178894,-4.73928144006791],[11.9505956298221,-4.74513382909484],[11.9630097887935,-4.76144957977036],[11.9713450098053,-4.78166692388763],[11.9711676652714,-4.80028816223999],[11.9566253650787,-4.81110621405591],[11.9532558071671,-4.81607187777756],[11.9539651880159,-4.82813134638045],[11.9527237723239,-4.83664391164237],[11.9465166926165,-4.8355798413414],[11.9454526223084,-4.83770798304538],[11.9472260726869,-4.84019081378106],[11.9468713825989,-4.84533382313415],[11.9484674887815,-4.85136355736969],[11.9449205872331,-4.85207293824232],[11.9399549231417,-4.8584573619753],[11.9440338614483,-4.86626054711651],[11.9435018261931,-4.8699847949076],[11.9784388153392,-4.92673523370809],[11.966911382287,-4.92975010104276],[11.9440338606908,-4.93755328588209],[11.9401390001187,-4.93293832817417],[11.9401209997833,-4.93291699987662],[11.9351390001649,-4.92701390830331],[11.9349635325599,-4.92680600029648],[11.9323604496326,-4.92372164764583],[11.9321497559016,-4.92347200017308],[11.932082000061,-4.92339171666724],[11.9319151342058,-4.92319399990373],[11.9318069998902,-4.92306587385167],[11.9316805118279,-4.92291600034039],[11.93152900006,-4.92273647609916],[11.9314475784323,-4.92263999978449],[11.9312499999444,-4.92240589257642],[11.9312129555816,-4.92236199982368],[11.9309719998215,-4.92207649516476],[11.9307437123301,-4.92180600019344],[11.930694,-4.92174709656689],[11.9305090901236,-4.92152799962849],[11.9304159995752,-4.92141769859373],[11.9302744681358,-4.92124999976564],[11.9301380003606,-4.92108830123738],[11.9293376683945,-4.92014000024498],[11.929306000271,-4.92010247667827],[11.9246477570624,-4.914583000295],[11.9245840000343,-4.91450745519498],[11.9244131350493,-4.91430499994726],[11.9243059999558,-4.91417805736589],[11.9218356674279,-4.9112510004434],[11.9215279997699,-4.91088645003857],[11.9213664233721,-4.91069500017521],[11.9212500003081,-4.91055705183099],[11.9211318007647,-4.91041699974382],[11.9209720002501,-4.91022765424891],[11.9208971792763,-4.91013900001114],[11.9206929999511,-4.90989707176237],[11.9192565109497,-4.90819500011769],[11.9190269998264,-4.90792305608146],[11.9190218893752,-4.90791699969188],[11.9187490003788,-4.90759365806059],[11.9185526450747,-4.90736100005306],[11.9184710003309,-4.90726425976194],[11.9183180232456,-4.90708299993265],[11.9181960003862,-4.90693841689138],[11.9180834007297,-4.90680499961555],[11.9179150002478,-4.90660546503396],[11.9178498686072,-4.90652829175892],[11.9176390003676,-4.90627843697244],[11.9176158441276,-4.906251000388],[11.9154170002186,-4.90364562565567],[11.9152704663521,-4.90347200042119],[11.9151390001839,-4.90331622761187],[11.9150358439248,-4.90319400022148],[11.9148610004533,-4.90298683019013],[11.9148012217113,-4.90291599982129],[11.9145830001183,-4.9026574315874],[11.9145665997157,-4.90263800012416],[11.9134730001369,-4.90134221090042],[11.9133951770975,-4.90124999977922],[11.9131950004116,-4.90101281360749],[11.9131605536847,-4.90097199979652],[11.9129170000896,-4.90068341694069],[11.9126913102067,-4.90041600012182],[11.9126390000637,-4.90035401908918],[11.9124566883399,-4.90013800043772],[11.912361000338,-4.90002462095644],[11.9122229150902,-4.89986100697546],[11.9120830000193,-4.89969522435344],[11.9119891311847,-4.89958399980914],[11.9118049999928,-4.89936582566227],[11.9117545090606,-4.89930600043306],[11.9115269722015,-4.89903639428599],[11.9112866525812,-4.89875164393781],[11.9112863628112,-4.8987512937359],[11.9112848249625,-4.8987500002884],[11.9112509999623,-4.89871957114917],[11.9112129282973,-4.89868532059981],[11.9109757980173,-4.89847200001073],[11.9109730000739,-4.89846948418368],[11.9101826129265,-4.89775845022099],[11.9097419190512,-4.89736200015433],[11.909648001785,-4.89727751167588],[11.9095830007924,-4.89721903581831],[11.9095404393864,-4.89718074695557],[11.9094328951105,-4.89708400019062],[11.9093464041205,-4.89700619327749],[11.9093050011577,-4.89696894560537],[11.9092074459572,-4.89688118496153],[11.9091238714091,-4.8968059999295],[11.9090406179117,-4.89673110440866],[11.9090290002357,-4.8967206516669],[11.9089243978163,-4.8966265509588],[11.9088148488518,-4.89652800027055],[11.9087489997514,-4.89646876085526],[11.9085058283353,-4.89625000030645],[11.9084730010312,-4.89622047004511],[11.9083142252501,-4.89607763185849],[11.9081968062566,-4.89597200005285],[11.9081950003605,-4.89597037707216],[11.9069629476405,-4.89486200031033],[11.9068690129387,-4.89477749393129],[11.9068070011294,-4.89472170692297],[11.8998239328491,-4.88843946095331],[11.8983051387863,-4.88707305929735],[11.8983036268198,-4.88707169881678],[11.8972367599944,-4.88332424803809],[11.8969625352724,-4.88236100019864],[11.8969159741851,-4.88219744674181],[11.8968060002158,-4.88181114806916],[11.8968042497247,-4.88180499995772],[11.896572529239,-4.88099103766348],[11.8959848925403,-4.87892684412608],[11.8959302230035,-4.87873480571024],[11.8945746954301,-4.87655339261808],[11.8944709432048,-4.87551781622368],[11.8948271528399,-4.87485999877717],[11.8948153059259,-4.87481838219328],[11.8942109919659,-4.87269553159],[11.892996893818,-4.86843052432975],[11.8927899128541,-4.86799310261333],[11.891350567754,-4.86495124197424],[11.8895987757104,-4.86124900043802],[11.889583000856,-4.86121566119795],[11.8895453320916,-4.86113604971159],[11.8895033921879,-4.86104741316245],[11.8894681821668,-4.86097299902895],[11.8891054497356,-4.86020638889593],[11.8886782498382,-4.85930352455583],[11.8881861042669,-4.85826340199749],[11.8875522394114,-4.85758411588984],[11.8872686360864,-4.85728957952509],[11.8872514758088,-4.85727160237916],[11.8871517639467,-4.8573537029071],[11.8858697562664,-4.85564731086083],[11.8806916171591,-4.84989205908242],[11.8802800036523,-4.84949723440951],[11.8798106059489,-4.84905956349536],[11.878894540505,-4.84818412178772],[11.8790222055061,-4.84803655364051],[11.8794601831839,-4.84758245076586],[11.8781386703445,-4.84603456829319],[11.8776185807508,-4.84647644647167],[11.8773751669998,-4.84668267699975],[11.8766998222927,-4.845913679636],[11.8755065933468,-4.84432525601754],[11.8746132847062,-4.84313607691728],[11.8740231520287,-4.8424801397323],[11.8657348836105,-4.83320151121751],[11.8633053134432,-4.83048163232462],[11.8618103436645,-4.82880795343432],[11.8573609998455,-4.8238266685922],[11.8573432234317,-4.82380676592848],[11.8572934118464,-4.82375099976994],[11.8570836986386,-4.82351620945704],[11.8570830000025,-4.82351542811578],[11.8570451042347,-4.82347299966823],[11.8543976938209,-4.82050899960262],[11.8543915976538,-4.82050252867811],[11.8543639722653,-4.82047322238678],[11.8537510002802,-4.81982294205839],[11.8535257671219,-4.81958400022114],[11.8534729991005,-4.81952801994181],[11.8532637166908,-4.81930600042406],[11.8531949999856,-4.81923310117301],[11.8530016655795,-4.81902800040083],[11.85291699931,-4.81893818034594],[11.8519136984432,-4.81787381437761],[11.850614568026,-4.81651351803981],[11.8498319033437,-4.81569399962319],[11.8495840012592,-4.8154344231753],[11.8495742036219,-4.81542416459671],[11.8495664071228,-4.81541600020708],[11.8490218723769,-4.81484582097049],[11.8481763061544,-4.81396042956332],[11.8481759316231,-4.81396003808418],[11.8470819998007,-4.81281457621849],[11.8462578811336,-4.81195163166696],[11.8461188031799,-4.81180600037507],[11.846080440817,-4.81176582956273],[11.8459720012484,-4.81165228013271],[11.84585331187,-4.81152800039064],[11.845742968058,-4.81141245655462],[11.8456940003568,-4.81136118102198],[11.8453434040493,-4.81099406509271],[11.8447932630979,-4.81041799963265],[11.8445840003247,-4.81019887623856],[11.8445574485087,-4.81017107350689],[11.8445277747024,-4.81014000028075],[11.8428427033392,-4.80837550769505],[11.8418227206374,-4.807214212817],[11.8393133358774,-4.80435712202103],[11.8373617399215,-4.80213508786184],[11.8373515226515,-4.80212345359433],[11.8372350652086,-4.80205540727212],[11.8370830580638,-4.80188542295633],[11.8370111170998,-4.80180497416568],[11.8368049994329,-4.80157448161538],[11.8363872536661,-4.8011073313709],[11.8362878000947,-4.80097299874608],[11.8362489992722,-4.80092058967045],[11.8360819810995,-4.80069499664934],[11.8360016893734,-4.80058654372245],[11.8359710024291,-4.80055160297101],[11.8358527823092,-4.80041699854918],[11.8358029695644,-4.80036028181146],[11.83569500202,-4.8002373521611],[11.8356454671302,-4.8001809513933],[11.8356086209435,-4.80013899741756],[11.8355394308601,-4.80006021836098],[11.8355386453374,-4.80005932348013],[11.8354170018697,-4.79992082066317],[11.835388284222,-4.79988812245146],[11.8353644615997,-4.79986099787868],[11.835275872484,-4.79976012945242],[11.8352751485048,-4.79975930569694],[11.8351390019992,-4.79960428980067],[11.8351248943217,-4.79958822697223],[11.8351203024689,-4.79958299813299],[11.8334730022417,-4.79770737313417],[11.833412951084,-4.797638999079],[11.8331949997867,-4.79739083770521],[11.8331679149414,-4.7973600001733],[11.8330547701689,-4.79723117174598],[11.8330543475461,-4.79723069009049],[11.8330540543353,-4.79723035608323],[11.8315270021367,-4.7957482762247],[11.8315005955267,-4.7957226466264],[11.8314710771059,-4.79569399845144],[11.8312892975286,-4.79551757290142],[11.8312510568116,-4.79548045917711],[11.8312446206535,-4.79547421146957],[11.8311846415298,-4.7954159982377],[11.8309730018739,-4.79521059139734],[11.8309171167201,-4.79515635221458],[11.8308982061815,-4.79513799776417],[11.8308694284562,-4.79511006751216],[11.8308687701053,-4.79510942960961],[11.8307510646924,-4.79499519023484],[11.8306950014162,-4.79494077736206],[11.8306762012179,-4.79492252996603],[11.8306380835492,-4.79488553402557],[11.8306117719652,-4.79485999793073],[11.83041700207,-4.79467096217488],[11.830325338881,-4.79458199873734],[11.8300844879885,-4.794348239925],[11.8300788114925,-4.79434272997459],[11.829381581032,-4.79366602499827],[11.8293813260074,-4.79366577666872],[11.8293819937527,-4.79366497785409],[11.8294958065592,-4.79352891068923],[11.8295914619841,-4.79341455030189],[11.8282877124252,-4.79202131593003],[11.8281659870028,-4.79190658527472],[11.8279126820615,-4.79166783250048],[11.8266674831745,-4.7904941651087],[11.8257568235322,-4.7895581636246],[11.8250743688777,-4.78885671466196],[11.8248958937954,-4.78856202783118],[11.8242559633458,-4.78750540922483],[11.8238065401312,-4.78661290790178],[11.8236817493449,-4.78495623177125],[11.8239371696821,-4.78010197362131],[11.8241187934111,-4.77643173024991],[11.8243987625669,-4.77436566270768],[11.8244007137614,-4.77430500022905],[11.8244020889039,-4.77426225715996],[11.8256502710304,-4.7743951617995],[11.8261603994427,-4.77486099955863],[11.8263224741633,-4.77500900306347],[11.8268050004528,-4.77510174438424],[11.8268369777728,-4.77510789056436],[11.8268520574109,-4.77439941072635],[11.8271551641384,-4.77449019278141],[11.8275679395929,-4.77447928672497],[11.827971519009,-4.77538013239652],[11.8300670549896,-4.77541689844718],[11.8317832776471,-4.77559387179903],[11.8319218274462,-4.77582337762904],[11.8320768250034,-4.77791959667513],[11.8328564618623,-4.77793447737422],[11.8328870362283,-4.77853430477403],[11.8327861637645,-4.778543924787],[11.8323612873958,-4.77853738866804],[11.8301389997974,-4.77855042632142],[11.8299747158082,-4.77855138965491],[11.8295829988481,-4.77854647586861],[11.8254169992806,-4.77849421341325],[11.8252429957929,-4.77849202967977],[11.8252416176524,-4.77849201277411],[11.8253981769244,-4.78469925113045],[11.8253987861531,-4.78469977539957],[11.8265889899715,-4.78572352109107],[11.8269973927976,-4.78568689475463],[11.827082999973,-4.7856617378031],[11.8273421766384,-4.78558557497227],[11.8273423960173,-4.78558613699268],[11.8273428029057,-4.78558717713274],[11.8274931138602,-4.78597200005086],[11.827493626347,-4.78597331173002],[11.8275180091413,-4.78603573559649],[11.827819172676,-4.78680676482529],[11.8283021416926,-4.78715608709444],[11.8286870502537,-4.78743448267717],[11.8287717919272,-4.78734317565663],[11.8290380079825,-4.78705633540359],[11.8292703433497,-4.78680599965872],[11.8292780211958,-4.78679772549721],[11.8292810252588,-4.78679448821528],[11.829284974484,-4.78679023321365],[11.8292867625753,-4.78678830662602],[11.8292874745827,-4.78678753925719],[11.8295829998267,-4.78675935481613],[11.8304407510365,-4.7866775486018],[11.8304407406998,-4.78667656826843],[11.8304256018395,-4.78527518091175],[11.830415276608,-4.78431936495313],[11.8304131145326,-4.78411920998485],[11.8304121298538,-4.78402800021448],[11.8304119658249,-4.78402709912757],[11.8304119105031,-4.78400772314623],[11.8304108475602,-4.78390930319007],[11.8304067004732,-4.7835252947694],[11.8303984192315,-4.78275835672233],[11.8305747555692,-4.78275871266659],[11.8305759427035,-4.78275871498558],[11.8309729986285,-4.78275951693975],[11.8312503772759,-4.78276007732583],[11.831250998764,-4.78276007836924],[11.8325354382104,-4.78276266740811],[11.8325354432006,-4.78276388088325],[11.8325377041422,-4.78331365016983],[11.8325377099022,-4.78331505068096],[11.8325370333721,-4.78331502547042],[11.8322239129427,-4.78330323589267],[11.8322230112002,-4.7833032016746],[11.8322236376339,-4.78332192740193],[11.8322258263081,-4.78338740827935],[11.8322277068385,-4.78344366406648],[11.8322286208785,-4.78347099963656],[11.8322295780581,-4.78349962623125],[11.832232603689,-4.78359012172226],[11.832235335571,-4.78367182577738],[11.832235890212,-4.78368842389121],[11.8322365105795,-4.78370698700024],[11.8322379596656,-4.78375031537193],[11.8322384162801,-4.78375030534987],[11.8322391412806,-4.78375028969913],[11.8322440541714,-4.78375018352561],[11.8322644577554,-4.78374974306857],[11.8323609998918,-4.78374765921802],[11.8333692065609,-4.78372589376451],[11.8334936651372,-4.7837232071421],[11.8337455263707,-4.78371776923187],[11.8337455368127,-4.78371811796664],[11.8337574666741,-4.78413247557401],[11.8337653201255,-4.78440523624332],[11.8337710014374,-4.78460256413795],[11.8337944217209,-4.78541599993297],[11.8338079927456,-4.78588731986864],[11.8338220126349,-4.78637419740168],[11.8344347930235,-4.78641448453627],[11.8345615446028,-4.78642281780166],[11.8345830006643,-4.7864242287985],[11.8354539074201,-4.78648148570591],[11.8361370303305,-4.78652639586363],[11.8374692149735,-4.78661397619662],[11.8375857360568,-4.78662163567778],[11.8393643592874,-4.78709446056834],[11.8401532993318,-4.78747648601006],[11.8405584038245,-4.78791789863368],[11.8411396848512,-4.78916771121277],[11.8419709364566,-4.79049354105001],[11.8427775404448,-4.79097623043202],[11.8432273980603,-4.79102148752264],[11.8432293200592,-4.79102168101903],[11.8432491212387,-4.79102367319955],[11.8446781748577,-4.79087248377648],[11.845640573761,-4.79057187534617],[11.8460453650829,-4.79039745315922],[11.8468059989348,-4.78993147877866],[11.8468395423571,-4.78991093034624],[11.8468826426967,-4.78986200014623],[11.8470820004174,-4.78963567915577],[11.8481656114972,-4.78840550676068],[11.8481659073375,-4.78840517121138],[11.8485512336515,-4.78796700515777],[11.8485996392718,-4.78791600000265],[11.8487500000314,-4.78775756434882],[11.8488623389788,-4.78763919186844],[11.8490279996072,-4.78746463534682],[11.8502285990642,-4.78619955534791],[11.8503947432729,-4.78602448727837],[11.8506244893367,-4.78561445074295],[11.8506779838034,-4.7853001071864],[11.8506995566667,-4.78504550521708],[11.8507413242654,-4.78455257016108],[11.8507403791707,-4.78455228676798],[11.8501380014488,-4.78437149630984],[11.8499197727093,-4.78430600020427],[11.8498600080295,-4.78428806323953],[11.8497061666432,-4.78424189068646],[11.8498599996683,-4.7836433668907],[11.850025707149,-4.7829986445696],[11.8501178873388,-4.78264000022889],[11.8501248536716,-4.78261289341513],[11.8501380009981,-4.78256174159995],[11.8501638302842,-4.78246124883157],[11.850189595732,-4.78236100029278],[11.8503431761915,-4.78176345917708],[11.850415999709,-4.78148012031409],[11.8505785790982,-4.78084756702079],[11.8513978223135,-4.77766012616999],[11.8514003359486,-4.7776605232128],[11.85195845099,-4.77774862903335],[11.8519586219403,-4.77774771482667],[11.852186755129,-4.77652700007889],[11.8528049664056,-4.77321904067585],[11.8529007913268,-4.77275005464172],[11.8530775650166,-4.77188488804558],[11.8531949986675,-4.77047354527268],[11.8532584687769,-4.76971075313935],[11.8532691817206,-4.76958199988724],[11.8532952283948,-4.76926897511504],[11.853401402077,-4.76799298691799],[11.85339653586,-4.76681451567246],[11.8533932984673,-4.76603034001626],[11.8533919306994,-4.76569899398413],[11.8533964015873,-4.76556262081857],[11.853408448889,-4.76519516992138],[11.8534162564771,-4.76495703085139],[11.8534317262305,-4.76448520332977],[11.8534477360958,-4.76399689543879],[11.8534729916578,-4.76322661016825],[11.8534742700363,-4.7631876173629],[11.8534729921112,-4.76317563701137],[11.8531849830048,-4.76047630751624],[11.8530575372348,-4.7597526176815],[11.8529270774274,-4.75901181958343],[11.852717130677,-4.75791500027275],[11.8526598971808,-4.75761599166201],[11.8526389999491,-4.75750682124149],[11.8526112793398,-4.75736199858932],[11.8523600003874,-4.75604924273627],[11.852345022824,-4.7559709999301],[11.8520819997805,-4.75459688901449],[11.8520815938726,-4.75459477004944],[11.8520814143738,-4.75459382928739],[11.8520794087528,-4.7545833563431],[11.8520793406369,-4.75458299972055],[11.8518764521737,-4.75352304412873],[11.8515500312965,-4.7526989805996],[11.8515471271798,-4.75269165032159],[11.8515293839156,-4.75264685677033],[11.8515289998389,-4.75264588342279],[11.851528327274,-4.75264418481004],[11.8514549060894,-4.7524588286463],[11.8514161550846,-4.75236099923804],[11.850576154886,-4.75024035975424],[11.8498524648144,-4.74841333621056],[11.8490280008751,-4.74676505227796],[11.8489851530506,-4.7466799559391],[11.8488442503233,-4.74640012395258],[11.8486550509082,-4.74602437525604],[11.8458793187927,-4.74197728470511],[11.845189842046,-4.7409720003896],[11.8451740116313,-4.74094891817742],[11.8451379999826,-4.74089641060313],[11.8440472252247,-4.73930599975627],[11.8440280008817,-4.73927796908015],[11.8438915568574,-4.73907902512835],[11.8438655857731,-4.73904370335957],[11.843855009322,-4.73902931881356],[11.8438542884077,-4.73902833870534],[11.8438540393477,-4.73902799999114],[11.8437500010809,-4.73888650298903],[11.8435809183995,-4.73865654200716],[11.843240825274,-4.73819400008611],[11.8431940003008,-4.73813031538381],[11.8431268249286,-4.73803895243519],[11.8430364227721,-4.73791599978829],[11.8429397824086,-4.73778456392083],[11.8429160013461,-4.73775222022714],[11.8428320168655,-4.73763800024781],[11.8426412088209,-4.73737848663887],[11.8426399997556,-4.73737684260901],[11.842639257105,-4.73737583186568],[11.8426276147518,-4.73735999962798],[11.8423619997187,-4.7369987477698],[11.8422202792116,-4.73680599958666],[11.8421123238283,-4.73665917436347],[11.8420840009412,-4.73662065262911],[11.8418124517598,-4.73625132867993],[11.8418114754498,-4.73624999993675],[11.8418095916716,-4.73624743884871],[11.8418060007139,-4.73624255539099],[11.8418053694659,-4.73624169688961],[11.8416070734113,-4.735972000324],[11.8415379078951,-4.73587793174357],[11.8415280117082,-4.73586447136395],[11.8414026706626,-4.73569399965042],[11.8414019669605,-4.73569304205378],[11.841250000424,-4.73548635731466],[11.8409938693567,-4.7351379996128],[11.8409839152418,-4.7351244626476],[11.8409720012731,-4.73510825918343],[11.8408279016028,-4.73491227260821],[11.8407909379872,-4.73486200013488],[11.8407608338426,-4.73482105588926],[11.840693999768,-4.73473015805499],[11.8406556604746,-4.73467801360619],[11.8405865387257,-4.73458400151837],[11.8405857218223,-4.7345828907785],[11.8404180001166,-4.73435477627102],[11.8403821369452,-4.73430600004141],[11.8364955766064,-4.72901989293022],[11.8335532111791,-4.72628728958883],[11.8297085549904,-4.72271672155658],[11.8268049998778,-4.72077575639211],[11.8266841936513,-4.72069500020977],[11.8265290012982,-4.7205912562159],[11.8262683260914,-4.72041699958274],[11.8262509998263,-4.72040541767551],[11.8257531511604,-4.72007261707717],[11.825801986359,-4.71986099993543],[11.8259425325986,-4.71925196277499],[11.8274575870586,-4.72032512586588],[11.8278363502343,-4.72101952531834],[11.8285307497214,-4.72120890659201],[11.8287832593469,-4.72171392533252],[11.8294776578456,-4.72146141558218],[11.8299826761325,-4.72089327125543],[11.829319839981,-4.72038825338994],[11.8290673311808,-4.71991479935427],[11.8292882772237,-4.71953603473933],[11.8297617307264,-4.71918883464546],[11.8301404936969,-4.71934665343626],[11.8312767852998,-4.71852599867952],[11.8317502392174,-4.71884163574695],[11.8322868212037,-4.71877850796237],[11.8323815115581,-4.718494435734],[11.8332021657589,-4.71852599924925],[11.8341490742551,-4.71783160039423],[11.8341490739915,-4.71694781761147],[11.8341490738386,-4.71612716370377],[11.8337387465664,-4.71587465469858],[11.8329812196124,-4.71603247306756],[11.8324165821216,-4.71525741087646],[11.8326971480622,-4.7127323214139],[11.8317993382942,-4.71093670162603],[11.8315187728382,-4.70902885614734],[11.8333143920015,-4.709028855848],[11.8335388444371,-4.7082432729116],[11.8315748861834,-4.70728935040627],[11.8311820944196,-4.70633542727552],[11.833089938673,-4.70577429572597],[11.832672209086,-4.70318062372171],[11.8335700182627,-4.70138500423802],[11.8351661236052,-4.70038743806972],[11.8356649084355,-4.69789352219991],[11.834667340812,-4.69520009264404],[11.8356649081278,-4.69360398695765],[11.8347670981923,-4.69160885524427],[11.8359641771765,-4.6901125045642],[11.8387573627419,-4.68801761635052],[11.8397549289982,-4.68582296987678],[11.842060415791,-4.68377241726863],[11.884977935035,-4.69157560225831],[11.9041312093642,-4.70753666312102]]]}})/auto/512x300?access_token=pk.eyJ1IjoiaG90IiwiYSI6IlBtUmNiR1kifQ.dCS1Eu9DIRNZGktc24IwtA) length is 22078 characters.

Here's an example of a valid [Mapbox URL](https://api.mapbox.com/styles/v1/hot/cj7hdldfv4d2e2qp37cm09tl8/static/geojson(%7B%22type%22:%22Feature%22,%22properties%22:%7B%7D,%22geometry%22:%7B%22type%22:%22Polygon%22,%22coordinates%22:[[[106.81419901549818,-6.2118787496559404],[106.81419901549818,-6.179167596769598],[106.86575509607793,-6.179167596769598],[106.86575509607793,-6.2118787496559404],[106.81419901549818,-6.2118787496559404]]]%7D%7D)/auto/512x300?access_token=pk.eyJ1IjoiaG90IiwiYSI6IlBtUmNiR1kifQ.dCS1Eu9DIRNZGktc24IwtA)

**Comment by pierrealixt** [comment]
From Nate
> The other thing is that geojsons of the form `{"type": "Feature".....}` aren’t accepted (returns an error parsing geojson error) whereas wrapping these around `{"type":"FeatureCollection"....}` makes them work (edited)
the erroring url is also of the former type

It doesn't seem to work:
- `{"type": "Feature"... }` => [it works](https://api.mapbox.com/styles/v1/hot/cj7hdldfv4d2e2qp37cm09tl8/static/geojson(%7B%22type%22:%22Feature%22,%22properties%22:%7B%7D,%22geometry%22:%7B%22type%22:%22Polygon%22,%22coordinates%22:[[[-9.15906877337727,38.73430398668146],[-9.156901566320565,38.73797380619023],[-9.158972400796866,38.74087564373503],[-9.162146957700447,38.74081345743774],[-9.166481021692247,38.74321635653337],[-9.148393791523038,38.74825784443306],[-9.14750401091015,38.74463549772588],[-9.130636192814098,38.74598087935218],[-9.130046205587535,38.74863865034037],[-9.113360396378647,38.73564226533931],[-9.107766711980707,38.73420117278674],[-9.10623069575872,38.73748769432832],[-9.103512522309625,38.73406829015476],[-9.096589043687963,38.731906821921754],[-9.099754353712886,38.72487174119024],[-9.105582232547045,38.71994017590302],[-9.113633880923405,38.70925733437763],[-9.135758655179362,38.697657696936304],[-9.149502286993293,38.69448770463988],[-9.15538840523324,38.72031621739592],[-9.160635560169036,38.72426586379724],[-9.15666216292844,38.72490799829991],[-9.160008277234727,38.72840542833026],[-9.15547514132008,38.73162236195118],[-9.15906877337727,38.73430398668146]]]%7D%7D)/auto/512x300?access_token=pk.eyJ1IjoiaG90IiwiYSI6IlBtUmNiR1kifQ.dCS1Eu9DIRNZGktc24IwtA)
- `{"type": "FeatureCollection"... }` => [it does not work](https://api.mapbox.com/styles/v1/hot/cj7hdldfv4d2e2qp37cm09tl8/static/geojson(%7B%22type%22:%22FeatureCollection%22,%22properties%22:%7B%7D,%22geometry%22:%7B%22type%22:%22Polygon%22,%22coordinates%22:[[[-9.15906877337727,38.73430398668146],[-9.156901566320565,38.73797380619023],[-9.158972400796866,38.74087564373503],[-9.162146957700447,38.74081345743774],[-9.166481021692247,38.74321635653337],[-9.148393791523038,38.74825784443306],[-9.14750401091015,38.74463549772588],[-9.130636192814098,38.74598087935218],[-9.130046205587535,38.74863865034037],[-9.113360396378647,38.73564226533931],[-9.107766711980707,38.73420117278674],[-9.10623069575872,38.73748769432832],[-9.103512522309625,38.73406829015476],[-9.096589043687963,38.731906821921754],[-9.099754353712886,38.72487174119024],[-9.105582232547045,38.71994017590302],[-9.113633880923405,38.70925733437763],[-9.135758655179362,38.697657696936304],[-9.149502286993293,38.69448770463988],[-9.15538840523324,38.72031621739592],[-9.160635560169036,38.72426586379724],[-9.15666216292844,38.72490799829991],[-9.160008277234727,38.72840542833026],[-9.15547514132008,38.73162236195118],[-9.15906877337727,38.73430398668146]]]%7D%7D)/auto/512x300?access_token=pk.eyJ1IjoiaG90IiwiYSI6IlBtUmNiR1kifQ.dCS1Eu9DIRNZGktc24IwtA)

**Comment by pierrealixt** [comment]
I'm using [this library](https://github.com/fitnr/visvalingamwyatt) to simplify polygons.
Here's the "complex" geojson:
<img width="546" alt="screen shot 2019-01-27 at 16 55 04" src="https://user-images.githubusercontent.com/35932320/51802617-8413d400-2254-11e9-8ccd-e8c19a6c9fb2.png">

After simplifying the geojson, MapBox returns a perfect thumbnail:
<img width="519" alt="screen shot 2019-01-27 at 16 56 55" src="https://user-images.githubusercontent.com/35932320/51802624-9a219480-2254-11e9-8d4c-9efabc548f9c.png">
