### ISSUE TITLE
Render ways like roads and waterways as lines on map 

### ISSUE THREAD

**Issue by smit1678** [hotosm/MapCampaigner#593]
It seems that lines like roads or waterways are drawn as polygons instead of lines. Ideally we would render these types of features on the map as lines. Example campaign for roads: https://campaigns.hotosm.org/campaign/be07e6a5a4194d57adf03ff848d80ac1

<img width="1376" alt="map campaigner - roads in lisbon 2018-11-07 14-21-33" src="https://user-images.githubusercontent.com/796838/48136818-88090900-e298-11e8-86f8-5293fd5dca51.png">

**Comment by PaulUithol** [comment]
@smit1678 , could we please prioritize this as per discussions with @jessbeutler? We're in quite urgent need of this for Open Cities

**Comment by timlinux** [comment]
Currently lines are available when you use the YAML config, so we would just need to propogate this function into the UI.

**Comment by timlinux** [comment]
Time estimate to add to ui: 3 hours

**Comment by jessbeutler** [comment]
Thanks, Tim! Looking forward to the UI option. Just knowing we can edit it in the YAML makes a big difference.
