### ISSUE TITLE
Delete a campaign

### ISSUE THREAD

**Issue by Cybereric** [hotosm/MapCampaigner#603]
Hello,
How can I **delete a campaign** ?
I created a campaign 15 days ago and it's still computing ! :-(
I think the problem is the same than this one described here >>> https://github.com/hotosm/MapCampaigner/issues/586

In fact I created two campaigns.
I had a 500 error during the validation so I reloaded the form :-/ and now there are two things that do not work at all :
- https://campaigns.hotosm.org/campaign/836d41cc4d5b464487c075f81e0dac5f
- https://campaigns.hotosm.org/campaign/cae1bae8281f4a84be78488d124c103b

**Comment by smit1678** [comment]
@Cybereric I deleted these two campaigns. I mentioned in the other ticket #586 that the geojson files you used were linestrings and the application needs to have polygons to compute. If you can change your input file to be polygons and then recreate these campaigns, they should. Let us know how it goes.

**Comment by Cybereric** [comment]
Thanks for deletion.
I answered here >>> https://github.com/hotosm/MapCampaigner/issues/586#issuecomment-441594317
It works :-)
