### ISSUE TITLE
Landing page: Show Map checkbox

### ISSUE THREAD

**Issue by smit1678** [hotosm/MapCampaigner#625]
Currently we have a Show Map checkbox. I'm not sure this provides useful functionality. The checkbox removes the map view on the page. 

![map-camp-map](https://user-images.githubusercontent.com/796838/51757474-5d6e6580-20bb-11e9-967d-ff978bbb499e.gif)

## Proposal
Let's remove the checkbox.

**Comment by JorgeMartinezG** [comment]
Pull request created https://github.com/hotosm/MapCampaigner/pull/635

**Comment by smit1678** [comment]
This was removed in #635. 👍
