### ISSUE TITLE
Edit Campaign: Projection

### ISSUE THREAD

**Issue by jessbeutler** [hotosm/MapCampaigner#634]
MC only seems to recognize WGS84 projections. When unknowingly uploading .geojsons that were not WGS84, it only told me that the size of AOI was too large. Would be helpful to have a note about using WGS84 projection here: 
![image](https://user-images.githubusercontent.com/36767434/52071371-d6087280-2550-11e9-8d89-a4f4b9c86361.png)
If possible, a warning saying the projection is not WGS84 when it rejects the file would be great as well.

**Comment by russbiggs** [comment]
the geojson standard specifies that they should always be in WGS84.  In the chance a non-compliant file is uploaded we can do this as a simple check, though likely wont be high priority.

**Comment by russbiggs** [comment]
After thinking about this more, there isn't a very straightforward way to test if a geojson isn't in WGS84.  Closing this since any alternative projection is non-compliant with the specification
