### ISSUE TITLE
Delete Type removes all types from Edit page

### ISSUE THREAD

**Issue by smit1678** [hotosm/MapCampaigner#676]
When testing out new features in #675, a new bug was introduced. When adding a new type and then deleting it, it removes all the types. This seems to happen not just on the templates but also on the custom form and yaml. Seen on both Chrome and Firefox. 

To replicate: 
- Edit campaign
- Add a new type and save
- Click the delete button on that new type

![mapcamp-delete-bug](https://user-images.githubusercontent.com/796838/54920193-844dea00-4efa-11e9-91b5-37df25e9194c.gif)

**Comment by willemarcel** [comment]
Another error that I noticed is that after removing one type, if you try to "add from template" again, the type options don't show on the page. 

![Screenshot_2019-03-25 Map Campaigner](https://user-images.githubusercontent.com/666291/54943810-dbf75000-4f10-11e9-9c99-d12dfe39c84a.png)
