### ISSUE TITLE
Switch campaign map visualization to vector tiles

### ISSUE THREAD

**Issue by willemarcel** [hotosm/MapCampaigner#683]
In order to allow the users to visualize large amounts of data, we need to replace the geojson data that is loaded on the campaign page map by vector tiles.

I followed [this tutorial](https://www.danieltrone.com/post/aws-vector-tiles-cloudfront/) and executed some tests. The first one was using the `Leaflet.VectorGrid` plugin to load the vector tiles. Then I replaced Leaflet by Mapbox-GL-JS.

The performance of Leaflet was not good, the interaction with the map is not fluid, but it worked great with `mapbox-gl-js`.

If you want to see it on action, download the html test files and open it in a browser:
* Mapbox-GL-JS: https://gist.github.com/willemarcel/57ffd255d001190fdbfd31cc8286e5e5
* Leaflet: https://gist.github.com/willemarcel/d6152bc7d0638f8463eecc43e6b510ac

Is it ok to replace Leaflet by Mapbox-GL-JS, @smit1678 ? I think it will not require too much work, as both apis are similar and the map code is very short and simple.

Related to https://github.com/hotosm/MapCampaigner/issues/496

**Comment by smit1678** [comment]
@willemarcel Thanks for the demos, that is a big difference. 

> Is it ok to replace Leaflet by Mapbox-GL-JS, @smit1678 ? I think it will not require too much work, as both apis are similar and the map code is very short and simple.

I think this makes sense. @JorgeMartinezG anything else to consider or add here?

**Comment by JorgeMartinezG** [comment]
@willemarcel @smit1678 I have two quick questions:

1. The examples read the information from a protocol buffer instead of geojson. This will imply that the geojson files will not be necessary, right?
2. If implemented in the project, will the code section of the map be written within the detail page? or be rendered using lambda function?

**Comment by willemarcel** [comment]
@JorgeMartinezG tippecanoe needs the geojson to produce the vector tiles. If we don't use the geojson for something else, we could delete it after the vector tiles generation.

We can render the page in the same way we currently do.

**Comment by willemarcel** [comment]
Published https://www.npmjs.com/package/@hotosm/geojson2vt to convert from GeoJSON to Vector Tiles.

I runned a test with a 360 MB buildings .osm file, which generated a 200 MB geojson and finally resulted on 45 MB of Vector Tiles.

So we can continue using lambda functions on all MapCampaigner processing stages.
