### ISSUE TITLE
The features attributes are not being pulled correctly

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/MapCampaigner#686]
It appears that the attributes associated with the tags listed are not being pulled through to MapCampaigner correctly: 

<img width="1280" alt="Screen Shot 2019-04-12 at 18 14 31" src="https://user-images.githubusercontent.com/8972913/56030424-6502e980-5d4f-11e9-9687-78c1578f46f0.png">

When you click on the way link, it takes you to the feature on OSM which shows that all the attributes are indeed present:

<img width="1280" alt="Screen Shot 2019-04-12 at 18 20 01" src="https://user-images.githubusercontent.com/8972913/56030525-9f6c8680-5d4f-11e9-9941-e3df797cd5e2.png">

This seems to be happening with several buildings across the METEOR Kathmandu campaigns:

Zone 1: https://campaigns.hotosm.org/campaign/88900da88213470e97a437f2399161db
Zone 2: https://campaigns.hotosm.org/campaign/085a2322e33a4b1b9c2101744c15db48
Zone 3: https://campaigns.hotosm.org/campaign/2ec9f24a5dbe49df8d75161932af948f
Zone 4: https://campaigns.hotosm.org/campaign/c4b1cdf329894306aa90369adff32770
Zone 5: https://campaigns.hotosm.org/campaign/d685b725bee24051b10f95a7c7d53d37
Zone 6: https://campaigns.hotosm.org/campaign/969eca6207b849f482a416ffebb4a412
Zone 7: https://campaigns.hotosm.org/campaign/880541fb5cb24fcdb48e2c0106358775

**Comment by smit1678** [comment]
I looked at the queries being sent to Overpass and it seems that the correct data is in Overpass. This was my original theory that maybe Overpass was missing this data. But since the data is being correctly pulled, then it seems that the data is not being correctly converted into a geojson file for rendering on the map. 

cc @willemarcel
