### ISSUE TITLE
geojson rendering incorrectly

### ISSUE THREAD

**Issue by russbiggs** [hotosm/MapCampaigner#713]
maybe related to #706 some features seem to have a geometry issue.  See this example:
<img width="266" alt="Screen Shot 2019-09-25 at 3 57 32 PM" src="https://user-images.githubusercontent.com/8487728/65585874-677b9780-dfad-11e9-9129-0739020dbe18.png">
You can see in the tiles behind the correct building footprint.  Seems like its losing nodes but still closing the polygon.

**Comment by willemarcel** [comment]
@russbiggs probably it's due to the fact the Mapbox data is not updated. Could you check on OSM which geometry is the most updated?

**Comment by russbiggs** [comment]
https://www.openstreetmap.org/way/676681869#map=19/35.08453/-106.62879

**Comment by russbiggs** [comment]
This happens in multiple places with similar geometry issues

<img width="673" alt="Screen Shot 2019-09-25 at 4 13 13 PM" src="https://user-images.githubusercontent.com/8487728/65587080-72372c00-dfaf-11e9-9163-21b266ca6683.png">

https://www.openstreetmap.org/way/672520790

**Comment by willemarcel** [comment]
@russbiggs I was considering that we are having some problems with the vector tiles generation, but I checked the Albuquerque campaign and noticed problems in the osm file (like isolated nodes that should be part of a building and incomplete buildings geometry). The osm file has 24 MB, but the conversion to geojson generated only one file of 50kb with some nodes missing. So we need to check on the logs what is causing those errors.

**Comment by russbiggs** [comment]
Thanks @willemarcel no need to rush on this.  currently want to just identify bugs before we begin new development.  I'll take a look at hte code a bit and let you know if any follow up is needed
