### ISSUE TITLE
Improvements to header

### ISSUE THREAD

**Issue by willemarcel** [hotosm/MapCampaigner#811]
* Increase font size of "Mapping our world together" phrase
* On the screenshare made by @russbiggs  I noticed the HOT logo wasn't well aligned vertically with the navigation links, but it worked well for me on Firefox and Chrome

**Comment by russbiggs** [comment]
Thanks @willemarcel do you know the font-size for "Mapping our world together"?

**Comment by willemarcel** [comment]
@russbiggs on TM we are using `1rem`. I tested locally `14px` on MapCampaigner and it seems good.
